global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'events-service'
    static_configs:
      - targets: ['events-service:8000']

  - job_name: 'features-service'
    static_configs:
      - targets: ['features-service:8000']

  - job_name: 'recommendation-service'
    static_configs:
      - targets: ['recommendation-service:8000']